# Generated by Django 2.0.7 on 2018-07-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('meet_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('meet_time',),
            },
        ),
        migrations.RemoveField(
            model_name='topic',
            name='events',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='topic',
            name='meetup_events',
            field=models.ManyToManyField(to='meetup.MeetupEvent'),
        ),
    ]
