# Generated by Django 2.0.7 on 2018-08-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_auto_20180714_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='meetup_events',
            new_name='meetup_event',
        ),
    ]
